config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Routes accessible without subdomain
  constraints(subdomain: '') do
    root 'public_pages#index'
    get 'about', to: 'public_pages#about'
    get 'contact', to: 'public_pages#contact'
    get '/hospital/index', to: 'hospital#index'
    get 'find', to: 'public_pages#find'
    post 'find', to: 'public_pages#check_email', as: 'check_email'
    get '/find/select_domain', to: 'hospital#select_domain', as: 'select_domain'
  end

  # Routes accessible with subdomain
  constraints(subdomain: /.+/) do
    resources :medicines do
      collection do
        get 'search'
        get 'search_medicines'
      end
    end

    resources :purchase_order do
      member do
        post 'add_medicine'
        put 'confirm'
        put 'deliver'
        get 'get_medicine'
        post 'remove_medicine'
      end
    end

    resources :prescriptions do
      member do
        post 'add_medicine'
      end
      collection do
        get 'search_medicine'
      end
      resources :prescribed_medicines, only: [:new, :create, :destroy]
    end
    
    resources :admin, only: [:show, :edit, :update]
    
    resources :appointments do
      collection do
        get 'show_availabilities'
      end
      member do
        put 'approve'
        put 'complete'
        put 'cancel'
      end
    end
    resources :bills do
      member do
        post 'add_medicine'
        post 'add_doctor'
        get 'get_medicine'
      end
    end
    resources :doctors do
      resources :availabilities, except: [:edit, :update, :show]
      collection do
        get 'speciality_filter'
      end
      collection do
        get 'search_doctors'
        get 'search'
      end
    end
    resources :patients do
      collection do
        get 'search_patients'
      end
    end
    get '' => 'dashboards#dashboard'
    get 'search' => 'hospital#search'
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords', sessions: 'users/sessions', confirmations: 'users/confirmations' }
  
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/bill.rb
class Bill < ApplicationRecord
  sequenceid :hospital, :bills
  belongs_to :hospital
  belongs_to :patient
  validates :billable_type, inclusion: { in: ['medicine', 'doctor'], message: 'Not a valid billable type' }
  has_many :bill_details, dependent: :destroy
  has_many :medicines, through: :bill_details, source: :billable, source_type: 'Medicine'
  has_many :doctors, through: :bill_details, source: :billable, source_type: 'Doctor'
  
  def add_medicine(medicine, quantity_added)
    begin
      Bill.transaction do
        if quantity_added > 0 && medicine.quantity > 0 && quantity_added <= medicine.quantity
          if medicine.update!(quantity: medicine.quantity - quantity_added)
            updated_price = price + (medicine.price * quantity_added)
            update!(price: updated_price)
            curr_bill_detail = bill_details.find_by(billable: medicine)
            if curr_bill_detail
              curr_bill_detail.update(quantity: quantity_added + curr_bill_detail.quantity)
            else
              bill_details.create(quantity: quantity_added, billable: medicine, hospital: medicine.hospital)
            end
          end
        else
          errors.add :base, I18n.t('medicine.add.failure')
          return false
        end
      end
    rescue => e
      errors.add :base, I18n.t('medicine.add.failure')
    end
  end

  def add_doctor(doctor)
    curr_bill_detail = bill_details.find_by(billable: doctor)
    if curr_bill_detail
      errors.add(:unable_to_add, I18n.t('doctor.add.failure'))
      return false
    else
      update(price: self.price + doctor.consultancy_fee)
      bill_details.create(billable: doctor, hospital: doctor.hospital)
    end
  end

  def medicine_bill?
    billable_type == 'medicine'
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :load_bill, only: :show
  load_and_authorize_resource find_by: :sequence_num, through: :current_hospital

  before_action :index_page_breadcrumb, only: %i[index new show edit]
  before_action :show_page_breadcrumb, only: [:show]

  # GET /bills
  def index
    @active_tab = params[:tab] == 'doctor' ? 'doctor' : 'medicine'
    @bills = @bills.includes(:patient)
    @doctor_bills = @bills.where(billable_type: 'doctor').paginate(page: params[:page1], per_page: PAGINATION_SIZE)
    @medicine_bills = @bills.where(billable_type: 'medicine').paginate(page: params[:page2], per_page: PAGINATION_SIZE)
    respond_to do |format|
      format.html
    end
  end

  # GET /bills/new
  def new
    add_breadcrumb t('sales_order.breadcrumb.new'), new_bill_path
    respond_to do |format|
      format.html
    end
  end
  
  def get_medicine
    @medicine = current_hospital.medicines.find_by(id: params[:search])
    if @medicine.blank?
      flash[:notice] = t('medicine.search.failure')
      redirect_to(request.env['HTTP_REFERER'])
    else
      respond_to do |format|
        format.js { render 'searchmed' }
      end
    end
  end

  def add_medicine
    @medicine = current_hospital.medicines.find_by(id: params[:medicine_id])
    quantity = params[:quantity].to_i
    if @bill.add_medicine(@medicine, quantity)
      flash.now[:notice] = t('sales_order.addmed.success')
    else
      flash.now[:error] = [t('sales_order.addmed.failure')]
      flash.now[:error] += @bill.errors.full_messages if @bill.errors.full_messages.present?
    end
    respond_to do |format|
      format.js { render 'bills/update_price' }
    end
  end

  def add_doctor
    @doctor = current_hospital.doctors.find_by(id: params[:doctor_id])
    if @bill.add_doctor(@doctor)
      respond_to do |format|
        flash[:notice] = [t('sales_order.adddoc.success')]
        format.js { render 'bills/update_price' }
      end
    else
      flash[:error] = [t('sales_order.adddoc.failure')]
      flash[:error] += @bill.errors.full_messages @bill.errors.full_messages.present?
      respond_to do |format|
        format.js { render 'bills/dont_update_price' }
      end
    end
  end

  # GET /bills/:id
  def show
    respond_to do |format|
      format.html
    end
  end

  # GET /bills/:id/edit
  def edit
    add_breadcrumb t('sales_order.breadcrumb.edit'), edit_bill_path
    respond_to do |format|
      format.html
    end
  end

  # POST /bills
  def create
    if @bill.save
      flash[:notice] = t('sales_order.add.success')
      redirect_to @bill
    else
      flash[:error] = [t('sales_order.add.failure')]
      flash[:error] += @bill.errors.full_messages if @bill.errors.full_messages.present?
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  # PATCH /bills/:id
  def update
    if @bill.update_attributes(bill_params)
      flash[:notice] = t('sales_order.update.success')
      redirect_to @bill
    else
      flash[:error] = [t('sales_order.update.failure')]
      flash[:error] += @bill.errors.full_messages if @bill.errors.full_messages.present?
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

    # DELETE /bills/:id
  def destroy
    if @bill.destroy
      flash[:notice] = t('sales_order.delete.success')
      redirect_to bills_path
    else   
      flash[:error] = [t('sales_order.delete.failure')]
      flash[:error] += @bill.errors.full_messages if @bill.errors.full_messages.present?
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  def bill_params
    params.require(:bill).permit(:billable_type, :patient_id)
  end

  def root_page_breadcrumb
    add_breadcrumb current_hospital.name, hospital_index_path
  end

  def index_page_breadcrumb
    add_breadcrumb t('sales_order.breadcrumb.index'), bills_path
  end

  def show_page_breadcrumb
    add_breadcrumb t('sales_order.breadcrumb.show'), bill_path
  end

  def load_bill
    @bill = Bill.includes(bill_details: [:billable]).find_by(sequence_num: params[:id])
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_doctorssearch.html.erb
<div class="container" id="docsearch">
  <%= form_tag(search_doctors_path, method: 'get', remote: true, class: 'navbar-form navbar-left') do %>
    <div class="input-group">
      <%= text_field_tag :search, nil, required: true, id: 'search_doctors', placeholder: "Search Doctors..." %>
      <%= hidden_field_tag :bill_sequence_num, @bill.sequence_num %>
      <div class="input-group-btn">
        <%= submit_tag t('submit'), class: 'btn btn-info glyphicon glyphicon-search',name: nil %>
      </div>
    </div>
  <% end %>
</div>
<div class="container" id="display_results"></div>

app/views/bills/_medicines_table.html.erb
<% if @bill.medicines.present? %>
  <table class="table">
    <thead>
      <tr>
        <th><%= t('medicine.name_label') %></th>
        <th><%= t('medicine.price_label') %></th>
        <th><%= t('medicine.quantity_label') %></th>
      </tr>
    </thead>
    <tbody>
    <% @bill.medicines.each do |medicine| %>
      <tr>
        <td><%= link_to medicine.name, medicine_path(medicine) %></td>
        <td><%= medicine.price %></td>
        <td><%= medicine_quantity(medicine) %></td>
      </tr>
    <% end %>
  <% else %>
    <strong><%= t('medicine.none') %></strong>
  <% end %>
  </tbody>
</table>

app/views/bills/_medicinesearch.html.erb
<div class="container" id="search1">
  <%= form_tag(get_medicine_bill_path, method: 'get', remote: true, class: 'navbar-form navbar-left') do %>
    <div class="input-group">
      <%= text_field_tag :search, nil, required: true, id: 'search_medicines', placeholder: "Search Medicines..." %>
      <%= hidden_field_tag :bill_sequence_num, @bill.sequence_num %>
      <div class="input-group-btn">
        <%= submit_tag t('submit'), class: 'btn btn-info glyphicon glyphicon-search',name: nil %>
      </div>
    </div>
  <% end %>
</div>

app/views/bills/dont_update_price.js.erb
$.prev_val = $('#bill_price').val();
if ($('#bill_price').val() == $.prev_val){
	  alert("Doctor already present!");
}

app/views/bills/edit.html.erb
<div id="add_medicine_flash_messages"></div>
<%= form_for @bill, url: {action: :update} do |f| %>
  <div class="container  pt-3">
      <div class="card">
        <div class="card-header p-3 container-fluid">
          <div class="row">
            <h3 class="col-md-9">
              <%= t('sales_order.edit_order_label') %>
            </h3>
          </div>
        </div>
        <div class="card-body">
          <p>
            <div class="form-group">
              <label><%= t('sales_order.name_label') %></label>
              <%= f.text_field :patient_id, required: true, class: "form-control", id: "patient_search1" %>
            </div>
            <div class="form-group">
              <label><%= "#{t('sales_order.price_label')}:" %></label>
              <strong><span class="pl-3" id="bill_price"><%= @bill.price %></span></strong>
            </div>
            <div class="form-group">
              <label><%= t('sales_order.type_label') %></label>
              <%= f.text_field :billable_type, readonly: true, class: "form-control" %>
            </div>
          </p>
        </div>
        <div class="card-footer p-3 container-fluid">
          <div class="row d-flex justify-content-md-end">
            <div class="col-md-3 d-flex justify-content-md-end">
              <%= link_to t('cancel'), bills_path , class: "btn btn-secondary btn-spacing" %>
              <%= f.submit t('update'), class: "btn btn-primary btn-spacing" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="container pt-3 mb-5">
  <div class="card">
    <div class="card-header p-3 container-fluid">
      <div class="row">
        <h3 class="col-md-9">
          <% if @bill.medicine_bill? %>
            <%= t('sales_order.add_medicines') %>
          <% else %>
            <%= t('sales_order.add_doctors') %>
          <% end %>
        </h3>
      </div>
    </div>
    <div class="card-body">
      <% if @bill.medicine_bill? %>
        <%= render 'medicinesearch' %>
      <% else %>
        <%= render 'doctorssearch' %>
      <% end %>
      <div id="display_results"></div>
    </div>
  </div>
</div>
<% if @bill.medicine_bill? %>
  <div class="container pt-3 mb-5">
    <div class="card">
      <div class="card-header p-3 container-fluid">
        <div class="row">
          <h3 class="col-md-9">
            <%= t('medicine.heading') %>
          </h3>
        </div>
      </div>
      <div class="card-body">
        <div id="medicines_table_bill">
          <%= render(partial: 'medicines_table') %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= javascript_tag do %>
  $('#patient_search1').tokenInput("/patients/search_patients", { preventDuplicates: true, theme: 'facebook', tokenLimit: 1, prePopulate: <%= [{id: @bill.patient_id, name: @bill.patient.name }].to_json.html_safe %>});
  $('.token-input-dropdown-facebook').css({"width": "69%", "font-size": "15px"});
  $('.token-input-list-facebook').css({"width": "100%", "font-size": "18px", "font-family": "Arial, Helvetica, sans-serif", "border-radius": "5px"});
<% end %>

app/views/bills/index.html.erb
<div class="container  pt-3">
  <div class="card">
    <div class="card-header p-3 container-fluid">
      <div class="row">
        <h3 class="col-md-10"><%= t('sales_order.heading') %></h3>
        <% if current_user.admin? %>
          <div class="col-md-2 d-flex justify-content-md-end">
            <%= link_to t('sales_order.add_order_label') , new_bill_path, class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
          <a class="<%= @active_tab == 'medicine' ? 'nav-link active' : 'nav-link' %>" data-toggle="tab" href="#medicine_bills"><%= t('medicine.heading') %></a>
        </li>
        <li class="nav-item">
          <a class="<%= @active_tab == 'doctor' ? 'nav-link active' : 'nav-link' %>" data-toggle="tab" href="#doctor_bills"><%= t('doctor.name') %></a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="medicine_bills" class="<%= @active_tab == 'medicine' ? 'container tab-pane active' : 'container tab-pane'%>"><br>
          <% if @medicine_bills.present? %>
            <table  class="table">
              <thead>
                <tr>
                  <th><%= t('sales_order.name_label') %></th>
                  <th><%= t('sales_order.type_label') %></th>
                  <th><%= t('sales_order.price_label') %></th>
                  <% if current_user.admin? %>
                    <th><%= t('action') %></th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <% @medicine_bills.each do |bill| %>
                  <td><%= link_to bill.patient.name, bill_path(bill) %></td>
                  <td><%= bill.billable_type %></td>
                  <td><%= bill.price %></td>
                  <% if can?(:edit, bill) %>
                    <div>
                      <td>
                        <%= link_to edit_bill_path(bill) do %>
                          <i class="fas fa-pen"></i>
                        <% end %>
                        <%= link_to bill_path(bill), method: :delete, class: "btn-spacing", data: { confirm: t('medicine.delete_confirm') } do %>
                          <i class="fas fa-trash-alt color-danger"></i>
                        <% end %>
                      </td>
                    </div>
                  <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <strong><%= t('sales_order.none') %></strong>
          <% end %>
          <br>
          <div class="pagination justify-content-center" class="pagination-spacing">
            <%= will_paginate @medicine_bills, previous_label: t('paginate.previous'), next_label: t('paginate.next'), params: { page2: @medicine_bills.next_page, tab:'medicine' } %>
          </div>
        </div>
        <div id="doctor_bills" class="<%= @active_tab == 'doctor' ? 'container tab-pane fade active show' : 'container tab-pane fade' %>"><br>
          <% if @doctor_bills.present? %>
            <table  class="table">
              <thead >
                <tr>
                  <th><%= t('sales_order.name_label') %></th>
                  <th><%= t('sales_order.type_label') %></th>
                  <th><%= t('sales_order.price_label') %></th>
                  <% if current_user.admin? %>
                    <th><%= t('action') %></th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
              <% @doctor_bills.each do |bill| %>
                <tr>
                  <td><%= link_to bill.patient.name, bill_path(bill) %></td>
                  <td><%= bill.billable_type %></td>
                  <td><%= bill.price %></td>
                  <% if can?(:edit, bill) %>
                    <div>
                      <td>
                        <%= link_to edit_bill_path(bill) do %>
                          <i class="fas fa-pen"></i>
                        <% end %>
                        <%= link_to bill_path(bill), method: :delete, class: "btn-spacing" do %>
                          <i class="fas fa-trash-alt color-danger"></i>
                        <% end %>
                      </td>
                    </div>
                  <% end %>
                </tr>
              <% end %>
            <% else %>
              <strong><%= t('sales_order.none') %></strong>
            <% end %>
            </tbody>
          </table>
          <br>
          <div class="pagination justify-content-center" class="pagination-spacing">
          <%= will_paginate @doctor_bills, previous_label: t('paginate.previous'), next_label: t('paginate.next'), params: { page1: @doctor_bills.next_page, tab:'doctor' } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bills/new.html.erb
<%= form_for @bill, url: {action: :create} do |f| %>
  <div class="container  pt-3">
      <div class="card">
        <div class="card-header p-3 container-fluid">
          <div class="row">
            <h3 class="col-md-9">
              <%= t('sales_order.add_order_label') %>
            </h3>
          </div>
        </div>
        <div class="card-body">
          <p>
            <div class="form-group">
              <label><%= t('sales_order.name_label') %></label>
              <%= f.text_field :patient_id, required: true, id: "patient_search", class: "form-control" %>
            </div>
            <div class="form-group">
              <label><%= t('sales_order.type_label') %></label>
              <%= f.select :billable_type, options_for_select(['medicine', 'doctor']), { selected: 'medicine', required: true, disabled: true }, { class: 'form-control', id: 'type_dropdown' } %>
            </div>
          </p>
        </div>
        <div class="card-footer p-3 container-fluid">
          <div class="row d-flex justify-content-md-end">
            <div class="col-md-3 d-flex justify-content-md-end">
              <%= link_to t('cancel'), bills_path , class: "btn btn-secondary btn-spacing" %>
              <%= f.submit t('create'), class: "btn btn-primary btn-spacing" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= javascript_tag do %>
  $('#patient_search').tokenInput("/patients/search_patients", { preventDuplicates: true, theme: 'facebook', tokenLimit: 1, hintText: 'search patient' });
  $('.token-input-dropdown-facebook').css({"width": "69%", "font-size": "15px"});
  $('.token-input-list-facebook').css({"width": "100%", "font-size": "18px", "font-family": "Arial, Helvetica, sans-serif", "border-radius": "5px"});
<% end %>

app/views/bills/searchdoc.js.erb
$('#display_results').html("<%=escape_javascript render partial:'doctors/search_results' %>")

app/views/bills/searchmed.js.erb
$('#display_results').html("<%= escape_javascript render partial:'medicines/search_results' %>")

app/views/bills/show.html.erb
<div class="container  pt-3">
    <div class="card">
      <div class="card-header p-3 container-fluid">
        <div class="row">
          <h3 class="col-md-8"><%= @bill.patient.name %></h3>
          <% if current_user.admin? %>
            <div class="col-md-4 d-flex justify-content-md-end">
              <%= link_to t('delete'), bill_path(@bill), method: :delete, class: "btn btn-danger", data: { confirm: t('medicine.delete_confirm') } %>
              <%= link_to t('edit'), edit_bill_path(@bill), class: "btn btn-primary btn-spacing" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="card-body">
      <dl class="row">
        <dt class="col-sm-2">
          <label><%= t('sales_order.name_label') %></label>
        </dt>
        <dd class="col-sm-9">
          <%= @bill.patient.name %>
        </dd>
        <dt class="col-sm-2">
          <label><%= t('sales_order.price_label') %></label>
        </dt>
        <dd class="col-sm-9">
          <%= @bill.price %>
        </dd>
        <dt class="col-sm-2">
          <label><%= t('sales_order.type_label') %></label>
        </dt>
        <dd class="col-sm-9">
          <%= @bill.billable_type %>
        </dd>
      </dl>
      <% if @bill.medicine_bill? %>
        <% if @bill.medicines.present? %>
          <dt class="col-sm-2">
            <label><%= t('medicine.heading') %></label>
          </dt>
          <dd>
            <table class="table">
              <thead>
                <tr>
                  <th>
                    <%= t('medicine.name_label') %>
                  </th>
                  <th>
                    <%= t('medicine.price_label') %>
                  </th>
                  <th>
                    <%= t('medicine.quantity_label') %>
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @bill.bill_details.each do |detail| %>
                  <tr>
                    <td>
                      <%= detail.billable.name %>
                    </td>
                    <td>
                      <%= detail.billable.price %>
                    </td>
                    <td>
                      <%= detail.quantity %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </dd>
        <% end %>
      <% else %>
        <% if @bill.bill_details.present? %>
          <dt class="col-sm-2">
            <label><%= t('doctor.appointments') %></label>
          </dt>
          <dd>
            <table class="table">
              <thead>
                <tr>
                  <th>
                    <%= t('doctor.name_label') %>
                  </th>
                  <th>
                    <%= t('doctor.fee') %>
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @bill.bill_details.each do |detail| %>
                  <tr>
                    <td>
                      <%= detail.billable.name %>
                    </td>
                    <td>
                      <%= detail.billable.consultancy_fee %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </dd>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
</div>

app/views/bills/update_price.js.erb
$('#bill_price').text("<%= @bill.price %>");
$('#medicines_table_bill').html("<%= escape_javascript(render(partial: 'medicines_table')) %>");
$('#add_medicine_flash_messages').html("<%= escape_javascript(render(partial: 'layouts/flash')) %>");