config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Routes accessible without subdomain
  constraints(subdomain: '') do
    root 'public_pages#index'
    get 'about', to: 'public_pages#about'
    get 'contact', to: 'public_pages#contact'
    get '/hospital/index', to: 'hospital#index'
    get 'find', to: 'public_pages#find'
    post 'find', to: 'public_pages#check_email', as: 'check_email'
    get '/find/select_domain', to: 'hospital#select_domain', as: 'select_domain'
  end

  # Routes accessible with subdomain
  constraints(subdomain: /.+/) do
    resources :medicines do
      collection do
        get 'search'
        get 'search_medicines'
      end
    end

    resources :purchase_order do
      member do
        post 'add_medicine'
        put 'confirm'
        put 'deliver'
        get 'get_medicine'
        post 'remove_medicine'
      end
    end

    resources :prescriptions do
      member do
        post 'add_medicine'
      end
      collection do
        get 'search_medicine'
      end
      resources :prescribed_medicines, only: [:new, :create, :destroy]
    end
    
    resources :admin, only: [:show, :edit, :update]
    
    resources :appointments do
      collection do
        get 'show_availabilities'
      end
      member do
        put 'approve'
        put 'complete'
        put 'cancel'
      end
    end
    resources :bills do
      member do
        post 'add_medicine'
        post 'add_doctor'
        get 'get_medicine'
      end
    end
    resources :doctors do
      resources :availabilities, except: [:edit, :update, :show]
      collection do
        get 'speciality_filter'
      end
      collection do
        get 'search_doctors'
        get 'search'
      end
    end
    resources :patients do
      collection do
        get 'search_patients'
      end
    end
    get '' => 'dashboards#dashboard'
    get 'search' => 'hospital#search'
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords', sessions: 'users/sessions', confirmations: 'users/confirmations' }
  
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  include ActiveModel::Transitions

  state_machine do
    state :drafted
    state :confirmed
    state :delivered
    event :confirm do
      transitions to: :confirmed, from: :drafted
    end
    event :deliver do
      transitions to: :delivered, from: :confirmed
    end
  end
  sequenceid :hospital, :purchase_orders
  validates :vendorname, presence: { message: 'must be given' }
  validates :price, presence: true, numericality: { greater_than: -1 }
  validates :state, presence: true
  belongs_to :hospital
  belongs_to :admin
  has_many :purchase_details, dependent: :destroy
  has_many :medicines, through: :purchase_details
  
  def add_medicine(medicine, quantity_added)
    begin
      PurchaseOrder.transaction do
        if quantity_added > 0 && self.update(price: self.price += medicine.price*quantity_added)
          curr_purchase_detail = purchase_details.find_by(medicine: medicine)
          if curr_purchase_detail
            updated_quantity = quantity_added + curr_purchase_detail.quantity
            curr_purchase_detail.update(quantity: updated_quantity)
          else
            purchase_details.create(quantity: quantity_added, medicine: medicine, hospital: medicine.hospital)
          end
        else
          self.errors.add(:base, I18n.t('medicine.add.failure'))
          return false
        end
      end
    rescue ActiveRecord::RecordNotSaved
      self.errors.add(:base, I18n.t('medicine.add.failure'))
    end   
  end
  
  def remove_medicine(medicine)
    begin
      PurchaseOrder.transaction do
        curr_purchase_detail = purchase_details.find_by(medicine: medicine)
        if curr_purchase_detail
          price = curr_purchase_detail.medicine.price * curr_purchase_detail.quantity
          if curr_purchase_detail.delete
            update(price: self.price - price)
          end
        else
          self.errors.add(:base, I18n.t('medicine.delete.failure'))
        end
      end
    rescue ActiveRecord::RecordNotSaved
      self.errors.add(:base, I18n.t('medicine.add.failure'))
      return false
    end
  end
end

app/controllers/purchase_order_controller.rb
class PurchaseOrderController < ApplicationController
  before_action :load_purchase_order, only: :show
  load_and_authorize_resource find_by: :sequence_num, through: :current_hospital

  before_action :index_page_breadcrumb, only: %i[index new show edit]
  before_action :show_page_breadcrumb, only: [:show]

  # GET /purchase_order
  def index
    @purchase_orders = @purchase_orders.paginate(page: params[:page], per_page: PAGINATION_SIZE)
    respond_to do |format|
      format.html
    end
  end

  # GET /purchase_order/new
  def new
    add_breadcrumb t('purchase_order.breadcrumb.new'), new_purchase_order_path
    respond_to do |format|
      format.html
    end
  end

  # GET /purchase_order/:id/get_medicine
  def get_medicine
    @medicine = current_hospital.medicines.find_by(id: params[:search])
    if @medicine.blank?
      flash[:notice] = t('medicine.search.failure')
    else
      respond_to do |format|
        format.js { render 'search' }
      end
    end
  end

  # PUT /purchase_order/:id/add_medicine
  def add_medicine
    @medicine = current_hospital.medicines.find_by(id: params[:medicine_id])
    quantity = params[:quantity].to_i
    if @purchase_order.add_medicine(@medicine, quantity)
        flash[:notice] = t('purchase_order.addmed.success')
    else
      flash[:error] = [t('purchase_order.addmed.failure')]
      flash[:error] += @purchase_order.errors.full_messages if @purchase_order.errors.full_messages.present?
    end
    respond_to do |format|
      format.js { render 'purchase_order/update_price' }
    end
  end

  # POST /purchase_order/:id/add_medicine
  def remove_medicine
    @medicine = current_hospital.medicines.find_by(id: params[:medicine_id])
    if @purchase_order.remove_medicine(@medicine)
      respond_to do |format|
        flash[:notice] = t('purchase_order.remove_medicine.success')
        format.js { render 'purchase_order/update_price' }
      end
    else
      flash[:error] = [t('purchase_order.remove_medicine.failure')]
      flash[:error] += @purchase_order.errors.full_messages if @purchase_order.errors.full_messages.present?
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  # GET /purchase_order/:id
  def show
    respond_to do |format|
      format.html
    end
  end

  # GET /purchase_order/:id/edit
  def edit
    add_breadcrumb t('purchase_order.breadcrumb.edit'), edit_purchase_order_path
    respond_to do |format|
      format.html
    end
  end

  # POST /purchase_order
  def create
    @purchase_order.hospital = current_hospital
    @purchase_order.admin = current_user
    if @purchase_order.save
      flash[:notice] = t('purchase_order.add.success')
      redirect_to @purchase_order
    else
      flash[:error] = [t('purchase_order.add.failure')]
      flash[:error] += @purchase_order.errors.full_messages if @purchase_order.errors.full_messages.present?
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  # PATCH purchase_order /:id
  def update
    if @purchase_order.update_attributes(purchase_order_params)
      flash[:notice] = t('purchase_order.update.success')
      redirect_to @purchase_order
    else
      flash[:error] = [t('purchase_order.update.failure')]
      flash[:error] += @purchase_order.errors.full_messages if @purchase_order.errors.full_messages.present?
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  # DELETE purchase_order /:id
  def destroy
    if @purchase_order.destroy
      flash[:notice] = t('purchase_order.delete.success')
      redirect_to purchase_order_index_path
    else
      flash[:error] = [t('purchase_order.delete.failure')]
      flash[:error] += @purchase_order.errors.full_messages if @purchase_order.errors.full_messages.present?
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  # PUT /purchase_order/:id/confirm
  def confirm
    if @purchase_order.confirm!
      flash[:notice] = t('purchase_order.confirm.success')
      redirect_to @purchase_order
    else
      flash[:error] = [t('purchase_order.confirm.failure')]
      flash[:error] += @purchase_order.errors.full_messages if @purchase_order.errors.full_messages.present?
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  # PUT /purchase_order/:id/deliver
  def deliver
    @purchase_order.purchase_details.each do |purchasedetail|
      purchasedetail.medicine.update(quantity: purchasedetail.medicine.quantity + purchasedetail.quantity)
    end
    if @purchase_order.deliver!
      flash[:notice] = t('purchase_order.deliver.success')
      redirect_to @purchase_order
    else
      flash[:error] = [t('purchase_order.deliver.failure')]
      flash[:error] += @purchase_order.errors.full_messages if @purchase_order.errors.full_messages.present?
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  def purchase_order_params   
    params.require(:purchase_order).permit(:vendorname, :price)
  end

  def root_page_breadcrumb
    add_breadcrumb current_hospital.name, hospital_index_path
  end

  def index_page_breadcrumb
    add_breadcrumb t('purchase_order.breadcrumb.index'), purchase_order_index_path
  end

  def show_page_breadcrumb
    add_breadcrumb t('purchase_order.breadcrumb.show'), purchase_order_path
  end

  def load_purchase_order
    @purchase_order = PurchaseOrder.includes(purchase_details: :medicine).find_by(sequence_num: params[:id])
  end
end

app/helpers/purchase_order_helper.rb
module PurchaseOrderHelper
  def print_state(purchase_order)
    if purchase_order.drafted?
      "<td><span class='rounded border border-light p-1 bg-light'>#{po.state}</span></td>".html_safe
    elsif purchase_order.confirmed?
      "<td><span class='rounded border border-warning p-1 bg-warning'>#{po.state}</span></td>".html_safe
    elsif purchase_order.delivered?
      "<td><span class='rounded border border-success p-1 bg-success'>#{po.state}</span></td>".html_safe
    end
  end
  
  def state_colors(purchase_order)
    if purchase_order.drafted?
      { text: 'warning', bg: 'pending' }
    elsif purchase_order.confirmed?
      { text: 'info', bg: 'approved' }
    else
      { text: 'success', bg: 'completed' }
    end
  end
end

app/views/purchase_order/_medicines_table.html.erb
<% if @purchase_order.medicines.present? %>
  <table  class="table">
    <thead >
      <tr>
        <th><%= t('medicine.name_label') %></th>
        <th><%= t('medicine.price_label') %></th>
        <th><%= t('medicine.quantity_label') %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @purchase_order.purchase_details.each do |detail| %>
        <tr>
          <td><%= link_to detail.medicine.name, medicine_path(detail.medicine) %></td>
          <td><%= detail.medicine.price %></td>
          <td><%= detail.quantity %></td>
          <td>
            <%= link_to remove_medicine_purchase_order_path(id: params[:id], medicine_id: detail.medicine.id), method: :post, data: { confirm: t('medicine.delete_confirm') }, remote: true do %>
              <i class="fas fa-trash-alt color-danger"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <strong><%= t('medicine.none') %></strong>
<% end %>

app/views/purchase_order/_medicinesearch.html.erb
<div class="container" id="search1">
  <%= form_tag(get_medicine_purchase_order_path, method: 'get', remote: true, class: 'navbar-form navbar-left') do %>
    <div class="input-group">
      <%= text_field_tag :search, nil, required: true, id: 'search_medicines', placeholder: "Search Medicines..." %>
      <%= hidden_field_tag :purchase_order_sequence_num, @purchase_order.sequence_num%>
      <div class="input-group-btn">
        <%= submit_tag t('submit'), class: 'btn btn-info glyphicon glyphicon-search', name: nil %>
      </div>
    </div>
  <% end %>
</div>

app/views/purchase_order/edit.html.erb
<div id="add_medicine_purchaseorder_flash_messages"></div>
<%= form_for @purchase_order, url: {action: :update} do |f| %>
  <div class="container  pt-3">
    <div class="card">
      <div class="card-header p-3 container-fluid">
        <div class="row">
          <h3 class="col-md-9">
            <%= t('purchase_order.edit_order_label') %>
          </h3>
        </div>
      </div>
      <div class="card-body">
        <p>
          <div class="form-group">
            <label><%= t('purchase_order.name_label') %></label>
            <%= f.text_field :vendorname, required: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <label><%= t('purchase_order.price_label') %></label>
            <strong><span class="pl-3" id="purchase_order_price"><%= @purchase_order.price %></span></strong>
          </div>
        </p>
      </div>
      <div class="card-footer p-3 container-fluid">
        <div class="row d-flex justify-content-md-end">
          <div class="col-md-3 d-flex justify-content-md-end">
            <%= link_to t('cancel'), purchase_order_index_path , class: "btn btn-secondary btn-spacing" %>
            <%= f.submit t('update'), class: "btn btn-primary btn-spacing" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% if can?(:update, @purchase_order) %>
  <div class="container pt-3 mb-5">
    <div class="card">
      <div class="card-header p-3 container-fluid">
        <div class="row">
          <h3 class="col-md-9">
            <%= t('purchase_order.add_medicine') %>
          </h3>
        </div>
      </div>
      <div class="card-body">
        <%= render 'medicinesearch'%>
        <div id="display_results"></div>
      </div>
    </div>
  </div>
  <div class="container pt-3 mb-5">
    <div class="card">
      <div class="card-header p-3 container-fluid">
        <div class="row">
          <h3 class="col-md-9">
            <%= t('medicine.heading') %>
          </h3>
        </div>
      </div>
      <div class="card-body">
        <div id="medicines_table_purchase_order">
          <%= render(partial: 'medicines_table') %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/purchase_order/index.html.erb
<div class="container  pt-3">
  <div class="card">
    <div class="card-header p-3 container-fluid">
      <div class="row">
        <h3 class="col-md-10"><%= t('purchase_order.heading') %></h3>
        <div class="col-md-2 d-flex justify-content-md-end">
          <%= link_to t('purchase_order.add_order_label'), new_purchase_order_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="card-body">
      <% if @purchase_orders.present? %>
        <table class="table">
          <thead>
            <tr>
              <th><%= t('purchase_order.id') %></th>
              <th><%= t('purchase_order.name_label') %></th>
              <th><%= t('purchase_order.price_label') %></th>
              <th><%= t('purchase_order.state_label') %></th>
              <th class='action'><%= t('action') %></th>
            </tr>
          </thead>
          <tbody>
            <% @purchase_orders.each do |purchase_order| %>
              <% state_colors = state_colors(purchase_order) %>
              <tr>
                <td><%= link_to purchase_order.sequence_num, purchase_order_path(purchase_order) %></td>
                <td><%= purchase_order.vendorname %></td>
                <td><%= purchase_order.price %></td>
                <td><span class="p-1 rounded text-<%= state_colors[:text] %> bg-<%= state_colors[:bg] %>"><%= purchase_order.state.capitalize %></span></td>
                <div>
                  <td>
                    <div class='row'>
                      <div class='col-sm'>
                        <% if can? :update, purchase_order %>
                          <%= link_to edit_purchase_order_path(purchase_order), class: 'float-right' do %>
                            <i class="fas fa-pen"></i>
                          <% end %>
                        <% end %>
                      </div>
                      <div class='col-sm'>
                        <% if can? :destroy, purchase_order %>
                          <%= link_to purchase_order_path(purchase_order), method: :delete,  data: { confirm: t('medicine.delete_confirm') } do %>
                            <i class="fas fa-trash-alt color-danger"></i>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </td>
                </div>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <strong><%= t('purchase_order.none') %></strong>
      <% end %>
    </div>
  </div>
</div>
<br>
<div class="pagination justify-content-center" class="pagination-spacing">
  <%= will_paginate @purchase_orders, previous_label: t('paginate.previous'), next_label: t('paginate.next') %>
</div>

app/views/purchase_order/new.html.erb
<%= form_for @purchase_order, url: { action: :create } do |f| %>
  <div class="container  pt-3">
      <div class="card">
        <div class="card-header p-3 container-fluid">
          <div class="row">
            <h3 class="col-md-9">
              <%= t('purchase_order.add_order_label') %>
            </h3>
          </div>
        </div>
        <div class="card-body">
          <p>
            <div class="form-group">
              <label><%= t('purchase_order.name_label') %></label>
              <%= f.text_field :vendorname, required: true, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.hidden_field :price, value: 0 %>
            </div>
            <div class="form-group">
              <label><%= t('purchase_order.state_label') %></label>
              <%= f.text_field :state, value: 'drafted', required: true, disabled: true, class: 'form-control' %>
            </div>
          </p>
        </div>
        <div class="card-footer p-3 container-fluid">
          <div class="row d-flex justify-content-md-end">
            <div class="col-md-3 d-flex justify-content-md-end">
              <%= link_to t('cancel'), purchase_order_index_path , class: "btn btn-secondary btn-spacing" %>
              <%= f.submit t('create'), class: "btn btn-primary btn-spacing" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/purchase_order/search.js.erb
$('#display_results').html("<%= escape_javascript render partial: 'medicines/search_results' %>")

app/views/purchase_order/show.html.erb
<div class="container  pt-3">
  <div class="card">
    <div class="card-header p-3 container-fluid">
      <div class="row">
        <h3 class="col-md-8"><%= "#{t('purchase_order.show_purchase_order')}#{@purchase_order.sequence_num}" %></h3>
        <div class="col-md-4 d-flex justify-content-md-end">
          <% if can?(:confirm, @purchase_order) %>
            <%= link_to t('purchase_order.confirm_button'), confirm_purchase_order_path(@purchase_order), method: "put", class: "btn btn-success" %>
           <% elsif can?(:deliver, @purchase_order) %>
              <%= link_to t('purchase_order.deliver_button'), deliver_purchase_order_path(@purchase_order), method: "put", class: "btn btn-success" %>
          <% end %>
          <% if can?(:update, @purchase_order) %>
           <%= link_to t('edit'), edit_purchase_order_path(@purchase_order), class: "btn btn-primary btn-spacing" %>
          <%end %>
          <% if can?(:destroy, @purchase_order) %>
            <%= link_to t('delete'), purchase_order_path(@purchase_order), method: :delete, class: "btn btn-danger btn-spacing", data: { confirm: t('medicine.delete_confirm') } %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-body">
      <dl class="row">
        <dd class="col-12">
          <% state_colors = state_colors(@purchase_order) %>
          <span class="p-1 rounded text-<%= state_colors[:text] %> bg-<%= state_colors[:bg] %>"><%= @purchase_order.state.capitalize %></span>
        </dd>
        <dt class="col-sm-2">
          <label><%= t('purchase_order.name_label') %></label>
        </dt>
        <dd class="col-sm-9">
          <%= @purchase_order.vendorname %>
        </dd>
        <dt class="col-sm-2">
          <label><%= t('purchase_order.price_label') %></label>
        </dt>
        <dd class="col-sm-9">
          <%= @purchase_order.price %>
        </dd>
      </dl>
      <label><strong><%= t('prescription.medicines') %>: </strong></label>
      <% if @purchase_order.medicines.present? %>
        <table  class="table">
          <thead >
            <tr>
              <th><%= t('medicine.name_label') %></th>
              <th><%= t('medicine.price_label') %></th>
              <th><%= t('medicine.quantity_label') %></th>
            </tr>
          </thead>
          <tbody>
            <% @purchase_order.purchase_details.each do |purchase_detail| %>
              <tr>
                <td><%= link_to purchase_detail.medicine.name, medicine_path(purchase_detail.medicine) %></td>
                <td><%= purchase_detail.medicine.price %></td>
                <td><%= purchase_detail.quantity%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <strong><%= t('medicine.none') %></strong>
      <% end %>
    </div>
  </div>
</div>

app/views/purchase_order/update_price.js.erb
$.PrevVal = $('#purchase_order_price').val()
$('#purchase_order_price').text("<%=@purchase_order.price%>");
if($.PrevVal < $('#purchase_order_price').val()){
  alert("Medicine added!");
}
if($.PrevVal > $('#purchase_order_price').val()){
  alert("Medicine removed!");
}
$('#medicines_table_purchase_order').html("<%= escape_javascript(render(partial: 'medicines_table')) %>");
$('#add_medicine_purchaseorder_flash_messages').html("<%= escape_javascript(render(partial: 'layouts/flash')) %>");