config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Routes accessible without subdomain
  constraints(subdomain: '') do
    root 'public_pages#index'
    get 'about', to: 'public_pages#about'
    get 'contact', to: 'public_pages#contact'
    get '/hospital/index', to: 'hospital#index'
    get 'find', to: 'public_pages#find'
    post 'find', to: 'public_pages#check_email', as: 'check_email'
    get '/find/select_domain', to: 'hospital#select_domain', as: 'select_domain'
  end

  # Routes accessible with subdomain
  constraints(subdomain: /.+/) do
    resources :medicines do
      collection do
        get 'search'
        get 'search_medicines'
      end
    end

    resources :purchase_order do
      member do
        post 'add_medicine'
        put 'confirm'
        put 'deliver'
        get 'get_medicine'
        post 'remove_medicine'
      end
    end

    resources :prescriptions do
      member do
        post 'add_medicine'
      end
      collection do
        get 'search_medicine'
      end
      resources :prescribed_medicines, only: [:new, :create, :destroy]
    end
    
    resources :admin, only: [:show, :edit, :update]
    
    resources :appointments do
      collection do
        get 'show_availabilities'
      end
      member do
        put 'approve'
        put 'complete'
        put 'cancel'
      end
    end
    resources :bills do
      member do
        post 'add_medicine'
        post 'add_doctor'
        get 'get_medicine'
      end
    end
    resources :doctors do
      resources :availabilities, except: [:edit, :update, :show]
      collection do
        get 'speciality_filter'
      end
      collection do
        get 'search_doctors'
        get 'search'
      end
    end
    resources :patients do
      collection do
        get 'search_patients'
      end
    end
    get '' => 'dashboards#dashboard'
    get 'search' => 'hospital#search'
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords', sessions: 'users/sessions', confirmations: 'users/confirmations' }
  
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/views/layouts/_breadcrumb.html.erb
<% if breadcrumbs.length > 0 %>
  <div class="breadcrumb breadcrumb-links breadcrumb-dark" >
    <% if breadcrumbs.length > 1 %>
      <div>
    <% else %>
      <div class="mr-1">
    <% end %>
      <%= link_to root_path do %>
        <i class="fas fa-home breadcrumb-icon"></i>
      <% end %>
      <span>/</span>
    </div>
    <%= render_breadcrumbs separator: " / ", class: "breadcrumb-item" %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<div class="container pt-3 <%= controller.class.send(:_layout) == 'static_pages_layout' ? 'mt-5' : '' %>">
  <% flash.each do |type, message| %>
    <% unless type == 'timedout' %>
      <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show">
        <button class="close" data-dismiss="alert">x</button>
        <% if message.is_a?(String) %>
          <%= message %>
        <% elsif message.is_a?(Array)%>
          <h5><strong><%= t('errors_msg') %></strong></h5>
          <ul>
            <% message.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="py-4 nav-static-pages text-white-50 fixed-bottom">
  <div class="container text-center">
    <small><%= link_to t('guest.home'), root_path, class: "text-white-50" %></small> |
    <small><%= link_to t('guest.about'), about_path, class: "text-white-50" %></small> |
    <small><%= link_to t('guest.contact'), contact_path, class: "text-white-50" %></small> |
  </div>
  <div class="container text-center">
    <small>Copyright &copy; Hospital Management System</small>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-color fixed-top">
  <%= link_to root_path, class:"navbar-brand col-2 font-weight-bold" do %>
    <% if user_signed_in? %>
      <%= current_hospital.name.titleize %>
    <% else %>
      <%= "HMS" %>
    <% end %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ">
      <%= form_tag search_path, method: :get, class: "form-inline my-2 my-lg-0" do %>
        <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2", placeholder: "Search" %>
        <%= submit_tag t('navbar.search'), class: 'btn btn-outline my-2 my-sm-0' %>
      <% end %>
    </ul>
  	<ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown pl-5">
        <% if user_signed_in? %>
          <a class="nav-link user-name dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle mr-1"></i>
            <%= current_user.name.titleize %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <div class="dropdown-divider color-primary"></div>
            <%= link_to user_profile_path(current_user) , class: "dropdown-item" do %>
              <i class="fas fa-user mr-2"></i><%= t('navbar.profile') %>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <i class="fas fa-sign-out-alt mr-2"></i><%= t('navbar.logout') %>
            <% end %>
          </div>
        <% else %>
          <%= link_to t('navbar.signup'), new_user_registration_path, class: 'btn btn-outline my-2 my-sm-0' %>
          <%= link_to t('navbar.login'), new_user_session_path, class: 'btn btn-outline my-2 my-sm-0' %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_public_pages_navbar.html.erb
<nav class="navbar nav-static-pages navbar-expand-lg navbar-light fixed-top">
  <%= link_to t('guest.hms'), root_url(subdomain: false), class: "navbar-brand text-white ml-3 mr-3" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to t('guest.about'), about_url(subdomain: false), class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to t('guest.contact'), contact_url(subdomain: false), class: "nav-link text-white" %>
      </li>
    </ul>
      <%= link_to t('guest.signin'), find_path, class: "btn btn-outline-light my-0 my-sm-0 mr-2" %>
      <%= link_to t('guest.signup'), new_user_registration_path, class: "btn btn-light my-0 my-sm-0 mr-3" %>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<!-- LEFT SIDEBAR -->
<div id="sidebar-nav" class="sidebar custom-sidebar">
  <div class="sidebar-scroll">
    <nav>
      <ul class="navbar-nav ">
        <%= render partial: 'layouts/sidebarentry', locals: {name: t('doctor.name'), call: Doctor, icon: 'fa-user-md', path: doctors_path} %>
        <%= render partial: 'layouts/sidebarentry', locals: {name: t('patient.name'), call: Patient, icon: 'fa-user-injured', path: patients_path} %>
        <%= render partial: 'layouts/sidebarentry', locals: {name: t('appointment.name'), call: Appointment, icon: 'fa-clock', path: appointments_path} %>
        <%= render partial: 'layouts/sidebarentry', locals: {name: t('prescription.name'), call: Prescription, icon: 'fa-prescription-bottle', path: prescriptions_path} %>
        <%= render partial: 'layouts/sidebarentry', locals: {name: t('availability.name'), call: Availability, icon: 'fa-calendar-alt', path: doctor_availabilities_path(current_user)} %>
        <%= render partial: 'layouts/sidebarentry', locals: {name: t('medicine.name'), call: Medicine, icon: 'fa-capsules', path: medicines_path} %>
        <%= render partial: 'layouts/sidebarentry', locals: {name: t('purchase_order.name'), call: PurchaseOrder, icon: 'fa-credit-card', path: purchase_order_index_path} %>
        <%= render partial: 'layouts/sidebarentry', locals: {name: t('sales_order.name'), call: Bill, icon: 'fa-cash-register', path: bills_path} %>
      </ul>
    </nav>
    <div class="container-fluid float-right-arrow ">
      <div class="navbar-btn d-flex justify-content-center btn-toggle-fullwidth "><i class="fas fa-arrow-circle-left arrow"></i>
      </div>
    </div>
  </div>
</div>
<!-- END LEFT SIDEBAR -->

app/views/layouts/_sidebarentry.html.erb
<% if can?(:index, call) %>
  <li class="pb-3 pt-3 side-bar-item">
    <%= link_to  path, class: 'sidebar-row' do %>
      <div class="row sidebar-nav-item text-light">
        <div class="col-1 ml-5 mr-1 sidebar-icon">
          <i class="fas <%= icon %>"></i>
        </div>
        <div class="col-8 mr-1 ml-1 sidebar-text">
          <span class=""><%= name %></span>
        </div>
      </div>
    <% end %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Hospital</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <div id="wrapper">
      <%= render partial: 'layouts/navbar' %>
      <% if signed_in?  %>
        <%= render partial: 'layouts/sidebar' %>
      <% end %>
      <div class="content-with-sidebar">
        <div class="container breadcrumb-row pl-3 border-bottom">
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <%= render partial: 'layouts/breadcrumb' %>
          </nav>
        </div>
        <div class="content">
          <%= render partial: 'layouts/flash', flash: flash %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/static_pages_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="static_pages_layout_background">
      <%= render partial: 'layouts/flash', flash: flash %>
    <%= yield %>
  </body>
</html>